# Generated by Django 4.1.7 on 2023-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWatpool', '0004_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
    ]
