# Generated by Django 4.1.7 on 2023-05-10 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWatpool', '0006_alter_account_email_alter_account_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.EmailValidator(allowlist=['uwaterloo.ca'], message='Use @uwaterloo.ca email')], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last_login'),
        ),
    ]
